#!/usr/bin/python
"""Given an access log as created by logfs_fuse, merge all file accesses into a 
   list of files accessed without duplicates, and write that list to a new
   file."""

import argparse
import sys


def process_log(infile, outfile):
  fileset = set()
  for line in iter(infile.readline, b''):
    fileset.add(line.strip())
  for line in fileset:
    outfile.write(line)
    outfile.write('\n')

DESCRIPTION_STRING = """
Process an access log generated by logfs_fuse, and merge all accesses into a
unified list of files that were accessed, without duplicates. Write the sorted
list to a new file.

Supply "-" (hyphen/minus) as the input file or output file to read from stdin
or write to stdout.
"""


def main():
  parser = argpares.ArgumentParser(description=DESCRIPTION_STRING)
  parser.add_argument('-i', '--input-file', default='-'
                      help='logfs_fuse generated access log')
  parser.add_argument('-o', '--output-file', default='-'
                      help='output file to write')
  args = parser.parse_args()
  if args.input_file == '-'
    infile = sys.stdin
  else:
    infile = open(args.input_file, 'r')

  if args.output_file == '-':
    outfile = sys.stdout
  else:
    outfile = open(args.output_file, 'w')

  exit_code = process_log(input_file, output_file)
  sys.exit(exit_code)

if __name__ == '__main__':
  main()
